apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: log-analyzer
spec:
  image: "ttl.sh/spinkube-log-analyzer-v2:2h"
  replicas: 2
  executor: containerd-shim-spin
---
apiVersion: v1
kind: Service
metadata:
  name: log-analyzer-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    core.spinkube.dev/app-name: log-analyzer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-analyzer-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-analyzer-svc
                port:
                  number: 80
