spin_manifest_version = 2

[application]
authors = ["DongHyeon Ko <hanser0204@naver.com>"]
description = ""
name = "app-python"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "app-python"

[component.app-python]
source = "app.wasm"
[component.app-python.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
